# Generated by Django 3.0.7 on 2020-08-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20200824_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='posts\\default\\default.jpg', upload_to='posts/%Y/%m/%d'),
        ),
    ]
